#!/bin/bash
#
#   Add package.json files to cjs/umd/esm subtrees
#
cat >dist/cjs/package.json <<!EOF
{
    "type": "commonjs"
}
!EOF

cat >dist/umd/package.json <<!EOF
{
    "type": "commonjs"
}
!EOF

cat >dist/esm/package.json <<!EOF
{
    "type": "module"
}
!EOF

# For type deifnition files (Dont have it yet)
# find src -name '*.d.ts' -exec cp {} dist/mjs \;
# find src -name '*.d.ts' -exec cp {} dist/cjs \;